---

common_pkgs:
  - curl
  - git
  - htop
  - jq
  - locales-all
  - proxychains
  - python3-dev
  - python3-pip
  - ncurses-term
  - nmap
  - rsync
  - sshpass
  - tcpdump
  - tmux
  - unzip
  - vim
  - wget
  - zsh
