language:  python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
before_install:
  - python3 -m pip install --upgrade pip
install:
  - python3 -m pip install .
after_success:
  - bash <(curl -s https://codecov.io/bash)
