---
- name: Full Configuration with Hardening
  hosts: all
  become: true
  collections:
    - devsec.hardening
  roles:
    - packages
    - configurations
    - firewall
    - ssh_hardening 
    - os_hardening 
    - geerlingguy.docker
    - geerlingguy.pip
