---
- name: VPS Hardening
  hosts: all
  user: root
  roles:
    - firewall
    - dev-sec.ssh-hardening 
    - dev-sec.os-hardening 
    - geerlingguy.docker
    - geerlingguy.pip
    - packages
    - configurations
