---
driver:
  name: vagrant
  driver_config:
    http_proxy: <%= ENV['http_proxy'] || nil %>
    https_proxy: <%= ENV['https_proxy'] || nil %>
  vagrantfiles:
    - kitchen_vagrant_block.rb

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  roles_path: ../ansible-os-hardening/
  playbook: tests/test.yml
  http_proxy: <%= ENV['http_proxy'] || nil %>
  https_proxy: <%= ENV['https_proxy'] || nil %>

transport:
  max_ssh_sessions: 1

platforms:
- name: ubuntu-16.04
  driver_config:
    box: bento/ubuntu-16.04
- name: ubuntu-18.04
  driver_config:
    box: bento/ubuntu-18.04
- name: centos-6
  driver_config:
    box: bento/centos-6.7
    provision: true
    vagrantfiles:
      - rhel6_provision.rb
- name: centos-7
  driver_config:
    box: bento/centos-7
- name: centos-8
  driver_config:
    box: bento/centos-8
- name: oracle-6
  driver_config:
    box: bento/oracle-6
    provision: true
    vagrantfiles:
      - rhel6_provision.rb
- name: oracle-7
  driver_config:
    box: bento/oracle-7
- name: debian-9
  driver_config:
    box: bento/debian-9
- name: debian-10
  driver_config:
    box: bento/debian-10
- name: amazon
  driver_config:
    box: bento/amazonlinux-2
- name: opensuse_tumbleweed
  driver_config:
    box: opensuse/Tumbleweed.x86_64
    provision: true
    vagrantfiles:
      - suse_provision.rb
  provisioner:
    ansible_binary_path: "/usr/local/bin"

verifier:
  name: inspec
  sudo: true
  inspec_tests:
    - https://github.com/dev-sec/linux-baseline/

suites:
- name: os
