name: Build on Push
on: 
  push:
    branches:
      - 'main'
 
jobs:
  # arm_builds:
  #   runs-on: ${{matrix.os}}
  #   strategy:
  #     matrix:
  #       os: ["buster"]
  #       platform: ["armv6", "armv7", "aarch64"]
  #       python-version: ["3.8.13", "3.9.13", "3.10.4"]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: uraimo/run-on-arch-action@v2.2.0
  #       name: Setup Python ${{ matrix.python-version }} on ${{ matrix.platform }}
  #       with:
  #         arch: ${{ matrix.platform }}
  #         distro: ${{ matrix.os }}
  #         githubToken: ${{ github.token }}
  #         shell: /bin/bash
  #         install: |
  #           apt-get update -q -y
  #           apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
  #               libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
  #               xz-utils tk-dev libffi-dev liblzma-dev git
  #           curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
  #           export PYENV_ROOT="$HOME/.pyenv"
  #           export PATH="$PYENV_ROOT/bin:$PATH"
  #           eval "$($HOME/.pyenv/bin/pyenv init -)"
  #           pyenv install ${{ matrix.python-version }}
  #           pyenv global ${{ matrix.python-version }}

  #     - name: Install Dependencies
  #       run: |
  #         python -m pip install flit
  #         python -m flit install

  #     - name: Build and Publish 
  #       run: |
  #         python -m flit build
 
  macos_builds:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["macos-latest"]
        platform: ["x64"]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform }}

      - name: Install Dependencies
        run: |
          python -m pip install flit
          python -m flit install

      - name: Build and Publish 
        run: |
          python -m flit build

  linux_builds:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        platform: ["x64"]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform }}

      - name: Install Dependencies
        run: |
          python -m pip install flit
          python -m flit install

      - name: Build and Publish 
        run: |
          python -m flit build
