---

- name: Update apt for Debian
  apt:
    update_cache: True

- name: Ugrade All (Debian)
  apt:
    only_upgrade: True

- name: Wait for APT Lock
  shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
